#!/bin/sh
cd ..

git add *
if [[ $? != 0 ]]; then 
   mail -s "add failed" msaharia@outlook.com
   exit 1
fi

git commit -a -m "Today's PDF"
if [[ $? != 0 ]]; then 
   mail -s "commit failed" msaharia@outlook.com
   exit 1
fi

git push
if [[ $? != 0 ]]; then 
   mail -s "push failed" msaharia@outlook.com
   exit 1
fi

mail -s "push ok" msaharia@outlook.com

